from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]
# Training scripts already build artifacts/bank_latest_reference.csv and forecasts.
print('Reference data is generated by scripts/train_eps.py')
